/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:           'var(--color-primary)',
        'primary-hover':   'var(--color-primary-hover)',
        'primary-muted':   'var(--color-primary-muted)',
        secondary:         'var(--color-secondary)',
        accent:            'var(--color-accent)',
        danger:            'var(--color-danger)',
        success:           'var(--color-success)',
        warning:           'var(--color-warning)',
        info:              'var(--color-info)',
        background:        'var(--color-background)',
        surface:           'var(--color-surface)',
        'surface-elevated':'var(--color-surface-elevated)',
        border:            'var(--color-border)',
        'border-strong':   'var(--color-border-strong)',
        text:              'var(--color-text)',
        'text-muted':      'var(--color-text-muted)',
        'text-subtle':     'var(--color-text-subtle)',
        'text-inverted':   'var(--color-text-inverted)',
        'text-disabled':   'var(--color-text-disabled)',
        'sidebar-bg':      'var(--color-sidebar-bg)',
        'sidebar-text':    'var(--color-sidebar-text)',
        'sidebar-active':  'var(--color-sidebar-active)',
        'sidebar-border':  'var(--color-sidebar-border)',
        'sidebar-hover':   'var(--color-sidebar-hover)',
      },
      fontFamily: {
        heading: 'var(--font-heading)',
        body:    'var(--font-body)',
        mono:    'var(--font-mono)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-base)',
        sm:      'var(--radius-sm)',
        md:      'var(--radius-md)',
        lg:      'var(--radius-lg)',
        xl:      'var(--radius-xl)',
        '2xl':   'var(--radius-2xl)',
        full:    'var(--radius-full)',
      },
      boxShadow: {
        sm:   'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-base)',
        md:   'var(--shadow-md)',
        card: 'var(--shadow-card)',
        lg:   'var(--shadow-lg)',
        xl:   'var(--shadow-xl)',
      },
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [],
}
